export const LIST_PORTS = [
    { code: "000101", description: "ASPARAGUS GREEN, FRESH", unit: "KG" },
    { code: "000103", description: "BAMBOO SHOOT FRESH", unit: "KG" },
    { code: "000104", description: "BASIL, FRESH", unit: "KG" },
    { code: "000105", description: "BEAN SPROUT FRESH", unit: "KG" },
    { code: "000106", description: "BEAN SPROUT LARGE (SOYA) FRESH", unit: "KG" },
    { code: "000107", description: "BEANS STRING FRESH", unit: "KG" },
    { code: "000108", description: "BEETROOT TOPPED, FRESH", unit: "KG" },
    { code: "000109", description: "BROCCOLI, FRESH", unit: "KG" },
    { code: "000110", description: "BRUSSELS SPROUT, FRESH", unit: "KG" },
    { code: "000111", description: "BURDOCK (GOBO), FRESH", unit: "KG" },
    { code: "000114", description: "CABBAGE CHINESE FRESH", unit: "KG" },
    { code: "000115", description: "CABBAGE HARD WHITE FRESH", unit: "KG" },
    { code: "000116", description: "CABBAGE RED, FRESH", unit: "KG" },
    { code: "000117", description: "CARROT TOPPED, FRESH", unit: "KG" },
    { code: "000118", description: "CAULIFLOWER TRIMMED, FRESH", unit: "KG" },
    { code: "000119", description: "CELERY TABLE, FRESH", unit: "KG" },
    { code: "000120", description: "CELERY JAPANESE (MITSUBA), FRESH", unit: "KG" },
    { code: "000121", description: "CHICORY, FRESH", unit: "KG" },
    { code: "000122", description: "CHIVES STEM, FRESH", unit: "KG" },
    { code: "000123", description: "CORN ON COB, FRESH", unit: "KG" },
    { code: "000124", description: "CUCUMBER, FRESH", unit: "KG" },
    { code: "000126", description: "DILL, FRESH", unit: "KG" },
    { code: "000129", description: "EGGPLANT, FRESH", unit: "KG" },
    { code: "000130", description: "ENDIVE FRESH", unit: "KG" },
    { code: "000131", description: "ENDIVE BELGIAN FRESH", unit: "KG" },
    { code: "000132", description: "FENNEL WEED FRESH", unit: "KG" },
    { code: "000134", description: "GARLAND CHRYSANTHEMUM, FRESH", unit: "KG" },
    { code: "000135", description: "GARLIC DRY", unit: "KG" },
    { code: "000136", description: "GINGER ROOT, FRESH", unit: "KG" },
    { code: "000137", description: "GINGER YOUNG (HAJIKAMI), FRESH", unit: "KG" },
    { code: "000140", description: "LEEK, FRESH", unit: "KG" },
    { code: "000141", description: "LETTUCE ICEBERG FRESH", unit: "KG" },
    { code: "000143", description: "LETTUCE SALAD, FRESH", unit: "KG" },
    { code: "000144", description: "LETTUCE SUNNY, FRESH", unit: "KG" },
    { code: "000145", description: "LOTUS ROOT, FRESH", unit: "KG" },
    { code: "000146", description: "MARJORAM, FRESH", unit: "KG" },
    { code: "000147", description: "MARROW JAPANESE TOGAN, FRESH", unit: "KG" },
    { code: "000148", description: "MINT LEAF, FRESH", unit: "KG" },
    { code: "000149", description: "MUSHROOM, FRESH", unit: "KG" },
    { code: "000151", description: "MUSHROOM STRAW (ENOKI, TAKE) FRESH", unit: "KG" },
    { code: "000152", description: "MUSHROOM DARK (SHIITAKE), FRESH", unit: "KG" },
    { code: "000154", description: "OKRA LADY FINGER, FRESH", unit: "KG" },
    { code: "000155", description: "ONION SCALLION, FRESH", unit: "KG" },
    { code: "000156", description: "ONION SPRING FRESH", unit: "KG" },
    { code: "000157", description: "ONION WHITE SMALL FRESH", unit: "KG" },
    { code: "000158", description: "ONION YELLOW DRY", unit: "KG" },
    { code: "000161", description: "PAC CHOI, FRESH", unit: "KG" },
    { code: "000162", description: "PARSLEY, FRESH", unit: "KG" },
    { code: "000163", description: "PEANUTS RAW", unit: "KG" },
    { code: "000164", description: "PEAS GREEN, FRESH", unit: "KG" },
    { code: "000165", description: "PEPPER BELL GREEN, FRESH", unit: "KG" },
    { code: "000166", description: "PEPPER BELL RED, FRESH", unit: "KG" },
    { code: "000167", description: "PEPPER CHILLI GREEN, FRESH", unit: "KG" },
    { code: "000168", description: "PEPPER CHILLI RED, FRESH", unit: "KG" },
    { code: "000169", description: "POTATO SELECTED FRESH", unit: "KG" },
    { code: "000170", description: "POTATO LARGE BAKING RUSSET FRESH", unit: "KG" },
    { code: "000171", description: "POTATO SWEET, FRESH", unit: "KG" },
    { code: "000172", description: "PUMPKIN, FRESH", unit: "KG" },
    { code: "000175", description: "RADISH RED, FRESH", unit: "KG" },
    { code: "000176", description: "RADISH WHITE (DAIKON), FRESH", unit: "KG" },
    { code: "000177", description: "ROSEMARY, FRESH", unit: "KG" },
    { code: "000180", description: "SAGE, FRESH", unit: "KG" },
    { code: "000182", description: "SPINACH, FRESH", unit: "KG" },
    { code: "000183", description: "SQUASH YELLOW", unit: "KG" },
    { code: "000185", description: "TARRAGON (ESTRAGON), FRESH", unit: "KG" },
    { code: "000186", description: "TARO (SATORIMO), FRESH", unit: "KG" },
    { code: "000187", description: "TOMATO SELECTED FRESH", unit: "KG" },
    { code: "000188", description: "TOMATO CHERRY RIPE, FRESH", unit: "KG" },
    { code: "000190", description: "TURNIP WHITE ROUND (KABU), FRESH", unit: "KG" },
    { code: "000191", description: "TURNIP YELLOW, FRESH", unit: "KG" },
    { code: "000194", description: "WATERCRESS, FRESH", unit: "KG" },
    { code: "000196", description: "YAM CHINESE (NAGAIMO), FRESH", unit: "KG" },
    { code: "000198", description: "ZUCCHINI (SQUASH), FRESH", unit: "KG" },
    { code: "000301", description: "ASPARAGUS SPEAR, QUICK FROZEN", unit: "KG" },
    { code: "000305", description: "BEANS BROAD, QUICK FROZEN", unit: "KG" },
    { code: "000307", description: "BEANS GREEN FRENCH CUT QUICK FROZEN", unit: "KG" },
    { code: "000308", description: "BEANS LIMA FORDHOOK QUICK FROZEN", unit: "KG" },
    { code: "000309", description: "BEANS STRING WHOLE, QUICK FROZEN", unit: "KG" },
    { code: "000311", description: "BEANS YELLOW WAX QUICK FROZEN", unit: "KG" },
    { code: "000315", description: "BROCCOLI, QUICK FROZEN", unit: "KG" },
    { code: "000316", description: "BRUSSELS SPROUT, QUICK FROZEN", unit: "KG" },
    { code: "000318", description: "CARROT WHOLE QUICK FROZEN", unit: "KG" },
    { code: "000319", description: "CARROT CHATEAU CUT, QUICK FROZEN", unit: "KG" },
    { code: "000320", description: "CARROT DICED, QUICK FROZEN", unit: "KG" },
    { code: "000321", description: "CAULIFLOWER, QUICK FROZEN", unit: "KG" },
    { code: "000323", description: "COLLARD GREENS, QUICK FROZEN", unit: "KG" },
    { code: "000324", description: "CORN ON COB, QUICK FROZEN", unit: "KG" },
    { code: "000326", description: "CORN KERNEL, QUICK FROZEN", unit: "KG" },
    { code: "000330", description: "HORSERADISH GRATED, QUICK FROZEN", unit: "PKT" },
    { code: "000333", description: "LOTUS ROOT, QUICK FROZEN", unit: "KG" },
    { code: "000334", description: "MIXED VEGETABLE, QUICK FROZEN", unit: "KG" },
    { code: "000337", description: "OKRA CUT, QUICK FROZEN", unit: "KG" },
    { code: "000338", description: "ONION RING BREADED, QUICK FROZEN", unit: "KG" },
    { code: "000341", description: "PEAS GREEN, QUICK FROZEN", unit: "KG" },
    { code: "000342", description: "PUMPKIN, QUICK FROZEN", unit: "KG" },
    { code: "000345", description: "RHUBARB, QUICK FROZEN", unit: "KG" },
    { code: "000348", description: "SPINACH, QUICK FROZEN", unit: "KG" },
    { code: "000352", description: "TARO (SATOIMO), QUICK FROZEN", unit: "KG" },
    { code: "000356", description: "ZUCCHINI SLICED, QUICK FROZEN", unit: "KG" },
    { code: "000361", description: "POTATO FRENCH FRY CRINKLE, QUICK FROZEN", unit: "KG" },
    { code: "005001", description: "APPLE TABLE (45~55'S)", unit: "KG" },
    { code: "005002", description: "APPLE TABLE (100'S)", unit: "KG" },
    { code: "005003", description: "APPLE TABLE (110~140'S)", unit: "KG" },
    { code: "005007", description: "APPLE TABLE GOLDEN DELICIOUS (32'S)", unit: "KG" },
    { code: "005015", description: "APRICOT, FRESH", unit: "KG" },
    { code: "005017", description: "AVOCADO, FRESH", unit: "KG" },
    { code: "005019", description: "BANANA HALF RIPE IMPORTED", unit: "KG" },
    { code: "005021", description: "CHERRY, FRESH", unit: "KG" },
    { code: "005026", description: "GRAPE CAMPBELL, FRESH", unit: "KG" },
    { code: "005027", description: "GRAPE DELAWARE, FRESH", unit: "KG" },
    { code: "005028", description: "GRAPE EMPEROR CALIFORNIA", unit: "KG" },
    { code: "005030", description: "GRAPE NEO-MUSCAT, FRESH", unit: "KG" },
    { code: "005033", description: "GRAPE FRUIT (36~40'S), FRESH", unit: "KG" },
    { code: "005035", description: "KIWI FRUIT (30~33'S)", unit: "KG" },
    { code: "005038", description: "LEMON IMPORTED (140~200'S)", unit: "KG" },
    { code: "005040", description: "LIME, FRESH", unit: "KG" },
    { code: "005041", description: "LYCHEE, FRESH", unit: "KG" },
    { code: "005042", description: "MANGO, FRESH", unit: "KG" },
    { code: "005044", description: "MELON SWEET CANTALOUPE, FRESH", unit: "KG" },
    { code: "005045", description: "MELON SWEET HONEYDEW, FRESH", unit: "KG" },
    { code: "005046", description: "MELON SWEET MUSK, FRESH", unit: "KG" },
    { code: "005047", description: "MELON SWEET PRINCE, FRESH", unit: "KG" },
    { code: "005048", description: "WATER MELON, FRESH", unit: "KG" },
    { code: "005051", description: "ORANGE MANDARIN, FRESH", unit: "KG" },
    { code: "005054", description: "ORANGE, FRESH", unit: "KG" },
    { code: "005057", description: "PEACH, FRESH", unit: "KG" },
    { code: "005058", description: "PAPAYA, FRESH", unit: "KG" },
    { code: "005059", description: "PEAR, FRESH", unit: "KG" },
    { code: "005061", description: "PEAR, JAPANESE, FRESH", unit: "KG" },
    { code: "005062", description: "PERSIMMON, FRESH", unit: "KG" },
    { code: "005063", description: "PINEAPPLE, FRESH", unit: "KG" },
    { code: "005064", description: "PLUM, FRESH", unit: "KG" },
    { code: "005065", description: "STRAWBERRY, FRESH", unit: "KG" },
    { code: "005081", description: "APRICOT HALVES, QUICK FROZEN", unit: "KG" },
    { code: "005083", description: "BLUEBERRY, QUICK FROZEN", unit: "KG" },
    { code: "005085", description: "BOYSENBERRY, QUICK FROZEN", unit: "KG" },
    { code: "005088", description: "RASPBERRY, QUICK FROZEN", unit: "KG" },
    { code: "005090", description: "STRAWBERRY, QUICK FROZEN", unit: "KG" },
    { code: "007004", description: "BONITO WHOLE, FROZEN", unit: "KG" },
    { code: "007007", description: "CODFISH HEADLESS, FROZEN", unit: "KG" },
    { code: "007008", description: "CODFISH FILLET, FROZEN", unit: "KG" },
    { code: "007010", description: "EEL WHOLE, FROZEN", unit: "KG" },
    { code: "007013", description: "FLOUNDER WHOLE, FROZEN", unit: "KG" },
    { code: "007014", description: "FLOUNDER FILLET, FROZEN", unit: "KG" },
    { code: "007016", description: "HADDOCK HEADLESS, FROZEN", unit: "KG" },
    { code: "007017", description: "HADDOCK FILLET, FROZEN", unit: "KG" },
    { code: "007018", description: "HAIR TAIL, FROZEN", unit: "KG" },
    { code: "007019", description: "HALIBUT HEADLESS, FROZEN", unit: "KG" },
    { code: "007020", description: "HALIBUT FILLET, FROZEN", unit: "KG" },
    { code: "007021", description: "HERRING, FROZEN", unit: "KG" },
    { code: "000725", description: "MACKEREL, FROZEN", unit: "KG" },
    { code: "000728", description: "MACKEREL HORSE, FROZEN", unit: "KG" },
    { code: "000729", description: "MACKEREL PIKE (SANMA), FROZEN", unit: "KG" },
    { code: "000733", description: "MULLET WHOLE, FROZEN", unit: "KG" },
    { code: "000738", description: "PLAICE FILLET, FROZEN", unit: "KG" },
    { code: "000740", description: "POMFRET WHOLE, FROZEN", unit: "KG" },
    { code: "000741", description: "POND SMELT (WAKASAGI), FROZEN", unit: "KG" },
    { code: "000743", description: "RAINBOW TROUT, FROZEN", unit: "KG" },
    { code: "000744", description: "RED FISH (GAROUPA) HEADLESS, FROZEN", unit: "KG" },
    { code: "000747", description: "SALMON WHOLE, FROZEN", unit: "KG" },
    { code: "000750", description: "SARDINE, FROZEN", unit: "KG" },
    { code: "000751", description: "SEABASS WHOLE, FROZEN", unit: "KG" },
    { code: "000752", description: "SEABASS FILLET, FROZEN", unit: "KG" },
    { code: "000753", description: "SNAPPER RED SMALL FROZEN", unit: "KG" },
    { code: "000754", description: "SNAPPER RED LARGE FROZEN", unit: "KG" },
    { code: "000758", description: "SOLE FISH, FROZEN", unit: "KG" },
    { code: "000763", description: "SWORD FISH, FROZEN", unit: "KG" },
    { code: "000769", description: "TUNA FISH FILLET, FROZEN", unit: "KG" },
    { code: "000781", description: "YELLOW FISH, FROZEN", unit: "KG" },
    { code: "000782", description: "YELLOW TAIL (BURI), FROZEN", unit: "KG" },
    { code: "000901", description: "ABALONE DRIED", unit: "KG" },
    { code: "000902", description: "ANCHOVY SALTED", unit: "KG" },
    { code: "000905", description: "CODFISH DRIED", unit: "KG" },
    { code: "000906", description: "CODFISH, SMOKED", unit: "KG" },
    { code: "000910", description: "COD ROE SALTED (MENTAIKO)", unit: "KG" },
    { code: "000912", description: "COMPOY (SCALLOP) DRIED", unit: "KG" },
    { code: "000917", description: "EEL, SMOKED OPEN BONELESS", unit: "KG" },
    { code: "000921", description: "HADDOCK FILLET, SMOKED", unit: "KG" },
    { code: "000923", description: "HERRING KIPPERED", unit: "KG" },
    { code: "000925", description: "JELLYFISH SALTED (SHIOKURAGE)", unit: "KG" },

];
